### PR TITLE
Refactor convert_float()

### PR DESCRIPTION
**Pull request by riedgar-ms**
Refactor `convert_float()` into utils. Although the two functions are slightly different, it turns out that `float("")` also raises a `ValueError`.

### CODE REVIEW

**Comment by riedgar-ms** [comment]
@slundberg @Harsha-Nori ?

**Review by nking-1 — APPROVED** [review]
LGTM. One thought - several of your edits here are small formatting fixes like adding whitespace and changing a single quote to double quote. We should consider picking a code formatter which will make this easier as the project grows.

**Comment by riedgar-ms** [comment]
> LGTM. One thought - several of your edits here are small formatting fixes like adding whitespace and changing a single quote to double quote. We should consider picking a code formatter which will make this easier as the project grows.

You may note that one of the commit comments features 'blacken' :-)

**Comment by Nking92** [comment]
Very cool, how did you run that? Is it part of Github Actions?

**Comment by riedgar-ms** [comment]
Ahhh no, I'm running it manually, just on files I feel I 'own' (whatever that means, exactly). I haven't dared run it on the full codebase yet (although I have seen how to exclude a particular commit from `git blame` so it doesn't wreck the history).

**Pull request closed without merging**
